<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="131" started-at="2020-07-21T15:20:41 EDT" finished-at="2020-07-21T15:20:41 EDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="131" started-at="2020-07-21T15:20:41 EDT" finished-at="2020-07-21T15:20:41 EDT">
      <class name="testclasses.TestNGITestResult">
        <test-method status="FAIL" signature="testMethod1()[pri:0, instance:testclasses.TestNGITestResult@57536d79]" name="testMethod1" duration-ms="49" started-at="2020-07-21T15:20:41 EDT" finished-at="2020-07-21T15:20:41 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at testclasses.TestNGITestResult.testMethod1(TestNGITestResult.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testclasses.TestNGITestResult@57536d79]" name="afterMethod" is-config="true" duration-ms="4" started-at="2020-07-21T15:20:41 EDT" finished-at="2020-07-21T15:20:41 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testMethod1 status=FAILURE method=TestNGITestResult.testMethod1()[pri:0, instance:testclasses.TestNGITestResult@57536d79] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="testMethod2()[pri:0, instance:testclasses.TestNGITestResult@57536d79]" name="testMethod2" duration-ms="2" started-at="2020-07-21T15:20:41 EDT" finished-at="2020-07-21T15:20:41 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testclasses.TestNGITestResult@57536d79]" name="afterMethod" is-config="true" duration-ms="0" started-at="2020-07-21T15:20:41 EDT" finished-at="2020-07-21T15:20:41 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testMethod2 status=SUCCESS method=TestNGITestResult.testMethod2()[pri:0, instance:testclasses.TestNGITestResult@57536d79] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testclasses.TestNGITestResult -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
